### ISSUE TITLE
Stop orders with Limit field empty - Different Limit price sent to Exchanges

### ISSUE THREAD

**Issue by MihaiPopescu1** [trailingcrypto/trailingcrypto#3]
Mihai Popescu, [30.09.20 23:36]
[ Photo ]
Do you have any idea why my Stop price (green line) was issued on Binance to buy at a lower price Limit (red line), so 23 st less?? The order failed to be executed (see chart here under). You can see in the order side (left side) I let Limit field empty. Previous similar order #6464709a was similar problem but a lesser difference (only 10 st.). 
You announced that empty Limit field means Limit price=Stop price. Should we fill it?
Insert the picture:
By choosing a file in PC:
![photo_2020-09-30_23-36-42](https://user-images.githubusercontent.com/72274468/94954898-bceb5e00-04b7-11eb-8062-fa13193e6aa7.jpg)

By copy image and paste here.
![image](https://user-images.githubusercontent.com/72274468/94955000-e3a99480-04b7-11eb-9744-aac2fe628332.png)

**Comment by Eternal-Sunshine** [comment]
`case 1:`
when entry price < stop price for LTE condition
then limit price = CURRENT PRICE

`case 2:`
when entry price > stop price for LTE condition
then limit price = STOP PRICE

The time between stop price is hit and limit order is sent to exchange (about few milliseconds) current price of given coin pair may change thereby some variation in stop price and limit price when limit price is kept empty is possible.

**Comment by MihaiPopescu1** [comment]
The error was benefic to buy lower, but I can't agree with this explanation only. That's why:
The order was issued at 23:19 at  second 10, when the current price was (as seen in next picture) a lot higher than the limit or even the stop.

![image](https://user-images.githubusercontent.com/72274468/94998548-8594b400-0580-11eb-8142-9b9440b604e8.png)

Price: H:0.0026896 L:0.0026857
so till the second 59 at same minut the minimum price was ...857, meaning **49 seconds, not few milliseconds** the price was completely greater than stop price 850
There was even another 14 sec in next minute till buy, at ...827, so no way the current price of minute 19:10 should influence the limit price for the next 64 seconds.
Checking with Binance, same time is reported, as 23:20:14" for limit buy, see here: 
![image](https://user-images.githubusercontent.com/72274468/94998849-f8069380-0582-11eb-997a-221128a66f03.png)
 
Applying the  formulas,  entry ...857 is > ...850 stop price, so case 2 should be applied, 
case 2: limit=stop 
which it wasn't.

ANYWAY, 

Still, **supposing case 1 is in effect**:
-   means entry price < stop price
    so
-   Limit=Stop price
   so, (SUPPOSING THAT IS TRUE) 
there is another BUG:

**why waiting _64 seconds_ to send buy order to exchange???**

In one case or another, there is a bug that should be fixed.

IMO, is the same bug that I found when we discussed a difference of 1 st, and you argued with same formula (in code), and again I say : 
** Current price IS NOT LAST PRICE **
or, more generally:
_Variables in formulas use a different {bid, last, ask} price._

Why? IMO:
Again, in this case was demanded STOP as LAST price. This is the price found in history tables and charts.
I asked a stop at ...850, but system check the current bid price as ...827, it copied my STop price but put the limit as given by your CASE 1: 
Current bid price = ...827 < Stop price ...850, so
Limit price = Current bid price = ...827
Is the only possible explanation.
Please asses.
Mihai
