### ISSUE TITLE
Missing display STOP value in SB in (Binance) futures

### ISSUE THREAD

**Issue by MihaiPopescu1** [trailingcrypto/trailingcrypto#6]
![image](https://user-images.githubusercontent.com/72274468/94985774-64ec4000-0527-11eb-9cec-1aee01f84bdc.png)

In Stop Buy, stop value is not displayed anymore, see picture.

**Comment by Eternal-Sunshine** [comment]
In attached screenshot. buy order type is `TRAILING STOP BUY` not `STOP BUY.` 
In TSB there is no fixed stop price and trailing starts immediately as soon as order is placed.
Moving stop price can be checked from comment section as it is visible in above image as well.

If you want to have a fixed stop price and then a trailing then use `STOP BUY with TRAILING exit` option

**Comment by MihaiPopescu1** [comment]
Agree.
